### ISSUE TITLE
Still Maintained? Need help?

### ISSUE THREAD

**Issue by jrjohnson** [suchitadoshi1987/ember-papaparse#5]
@suchitadoshi1987 are you still maintaining this library? Would you like some help? I'm interested in updating the configuration to pull papaparse from NPM as it is my last bower dependency and would be happy to help with other maintenance.

**Comment by jrjohnson** [comment]
Bump @suchitadoshi1987

**Comment by rwwagner90** [comment]
@suchitadoshi1987 bump again! This is also our last bower dependency. If you would please add us as collaborators, we can get this fixed up.

**Comment by suchitadoshi1987** [comment]
@jrjohnson I have added you as the collaborators. Sorry was a little caught up with other stuff, let me know if you need anything else!

**Comment by suchitadoshi1987** [comment]
@rwwagner90 added you as well! Thank you :)

**Comment by jrjohnson** [comment]
Excellent. Thanks. I will have a PR in to update ember-cli ASAP.
